services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_DEBUG=0
      - HOST=0.0.0.0
      - PORT=5000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "3001:3000"
    depends_on:
      backend:
        condition: service_started
    environment:
      - RAILS_ENV=production
      - RACK_ENV=production
      - PORT=3000
      - WEB_CONCURRENCY=0
      - RAILS_MAX_THREADS=2
      - RAILS_MIN_THREADS=2
      - RAILS_SERVE_STATIC_FILES=true
      - SECRET_KEY_BASE=please-change-me-in-production
      - PLAGIARISM_API_URL=http://backend:5000/api/compare
    restart: unless-stopped

networks:
  default:
    driver: bridge